# Generated by Django 4.2.17 on 2024-12-20 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='address',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usermodel',
            name='city',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usermodel',
            name='street',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usermodel',
            name='userimg',
            field=models.ImageField(blank=True, null=True, upload_to='userimg/'),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='zipcode',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
